#!/bin/bash
#
# Run roundup tests for spark.
#

type -t roundup >/dev/null || {
  cat <<MESSAGE 1>&2 ;
error: roundup missing

Check out https://github.com/bmizerany/roundup for instructions on installing roundup.
MESSAGE

  exit 1;
}

roundup ./*-test.sh
