#!/bin/bash -e
#
# Run roundup tests for spark.
#

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }

type -t roundup >/dev/null || {
  cat <<MESSAGE 1>&2 ;
error: roundup missing

Check out https://github.com/bmizerany/roundup for instructions on installing roundup.
MESSAGE

  exit 1;
}

cd "$scriptDir"
roundup ./*-test.sh
