name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt update && sudo apt install --yes bc
        curl -L https://github.com/bmizerany/roundup/tarball/v0.0.6 | tar xvzf -
        (cd bmizerany-roundup-f526c39 && ./configure && make && sudo make install)
        ./tests/test
